<Project>
  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <LangVersion>latest</LangVersion>
    <Product>Icon Replacer</Product>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/gvastethecreator/icon-replacer</RepositoryUrl>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DefineConstants Condition="'$(ICON_REPLACER_DISTRIBUTION_CHANNEL)' == 'store'">$(DefineConstants);ICON_REPLACER_STORE</DefineConstants>
  </PropertyGroup>
</Project>
